fix: 'jenkins.io/host' annotation should take precedence
jenkins-x/jx-helpers pull request #402
Opened 2023-04-11 03:44 UTC by yelhouti

2023-04-11 03:45 UTC, yelhouti commented
@ankitm123 could you please check this

2023-04-11 03:45 UTC, yelhouti commented
/assign @ankitm123

2023-09-25 08:25 UTC, msvticket commented
@yelhouti Please add a description on why this PR is needed

2023-09-25 08:30 UTC, yelhouti commented
@msvticket Is this clear enough ?

2023-09-25 08:46 UTC, msvticket commented
> @msvticket Is this clear enough ?

Yeah, now the use case is clear

2023-09-25 08:52 UTC, msvticket requested changes
You should give precedence for ing.Spec.TLS.Hosts over ing.Spec.Rules.Host since you might not have certificates for all hosts in ing.Spec.Rules.Host, so returning a https url for the first ing.Spec.Rules.Host might give an invalid url.

Your change would cause problems if you have multiple

2023-09-25 08:55 UTC, yelhouti commented
@msvticket The way I see it is:
1. either you have TLS enable in staging and it should be configured correctly
2. TLS is disabled and I don't use it.

2023-10-04 11:36 UTC, msvticket commented
The case I describe is not a case of incorrect configuration

2024-10-23 13:34 UTC, closed without merging

2024-10-23 13:34 UTC, msvticket commented
PR is abandoned