feat: add function for sparse & partial clone of cluster repo
jenkins-x/jx-helpers pull request #420
Opened 2024-10-16 13:17 UTC by GavinPJK

Create `func PartialCloneClusterRepo`, which attempts:

- a sparse clone of cluster repo (`SparseCloneToDir`)
- if the sparse clone fails, fall back to a partial clone (`PartialCloneToDir`)
- if the partial clone fails, fall back to a full clone (`CloneToDir`)

This ensures the git clone is successful, even if the upstream provider doesn't support `git-sparse-checkout` or `--filter=blob:none`. See: #https://github.com/jenkins-x/jx/issues/8240#issuecomment-1467944694

2024-10-16 13:17 UTC, GavinPJK commented
/cc @msvticket

2024-10-18 12:13 UTC, msvticket requested changes
Have you tested that failures actually are detected in PartialCloneClusterRepo and the fallbacks are used?

2024-10-18 12:16 UTC, msvticket commented
/ok-to-test

2024-10-22 15:31 UTC, GavinPJK commented on pkg/gitclient/helpers.go
> +	sparseCloneArgs := []string{"clone", "--filter=blob:none"}
Amended

2024-10-22 15:41 UTC, GavinPJK commented
> Have you tested that failures actually are detected in PartialCloneClusterRepo and the fallbacks are used?

Hi @mvsticket,

I've completed local tests by running the `PartialCloneClusterRepo` command within separate git environments. The fallback mechanisms are working as-intended.


Namely, I ran `PartialCloneClusterRepo` for 3 git versions: 2.45.2 (sparse checkout & filters supported); 2.22.5 (sparse checkout unsupported); 2.8.6 (sparse checkout and filters unsupported)

For git version `2.45.2`:
```
$ docker run --rm --network host -v ~/.ssh:/root/.ssh -v $(pwd):/workspace clone-test-2.45.2
about to run: git clone --no-checkout --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-3744212911 in dir /tmp
Cloning into '/tmp/jx-git-3744212911'...
about to run: git sparse-checkout set --no-cone .jx/gitops/source-config.yaml in dir /tmp/jx-git-3744212911
about to run: git checkout in dir /tmp/jx-git-3744212911
Repository cloned to directory: /tmp/jx-git-3744212911
Your branch is up to date with 'origin/gitops-upgrade-20241014'.
```
Only `.jx/gitops/source-config.yaml` was cloned in this case

For git version `2.22.5`:

```
$ docker run --rm --network host -v ~/.ssh:/root/.ssh -v $(pwd):/workspace clone-test-2.22.5
about to run: git clone --no-checkout --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-900025729 in dir /tmp
Cloning into '/tmp/jx-git-900025729'...
about to run: git sparse-checkout set --no-cone .jx/gitops/source-config.yaml in dir /tmp/jx-git-900025729
git: 'sparse-checkout' is not a git command. See 'git --help'.
WARNING: failed sparse clone of cluster git repo ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/: failed to set sparse checkout patterns to [.jx/gitops/source-config.yaml]: failed to run 'git sparse-checkout set --no-cone .jx/gitops/source-config.yaml' command in directory '/tmp/jx-git-900025729', output: 'git: 'sparse-checkout' is not a git command. See 'git --help'.'
WARNING: falling back to partial clone without checkout patterns
about to run: git clone --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-70191649 in dir /tmp
Repository cloned to directory: /tmp/jx-git-70191649
Cloning into '/tmp/jx-git-70191649'...
Checking out files: 100% (3059/3059), done.
```
The cluster repo was only partially cloned in this case using the fallback - all the files from the HEAD were cloned locally (`--no-checkout` flag is not present in the clone)

For git version `2.8.6`:

```
$ docker run --rm --network host -v ~/.ssh:/root/.ssh -v $(pwd):/workspace clone-test-2.8.6
about to run: git clone --no-checkout --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-3833591101 in dir /tmp
error: unknown option `filter=blob:none'
usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
[.....]
    -6, --ipv6            use IPv6 addresses only
WARNING: failed sparse clone of cluster git repo ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/: failed to clone repository ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ to directory: /tmp/jx-git-3833591101: failed to run 'git clone --no-checkout --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-3833591101' command in directory '/tmp', output: 'error: unknown option `filter=blob:none'
usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
[...]
    -6, --ipv6            use IPv6 addresses only'
WARNING: falling back to partial clone without checkout patterns
about to run: git clone --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-1657329244 in dir /tmp
error: unknown option `filter=blob:none'
usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
[...]
    -4, --ipv4            use IPv4 addresses only
    -6, --ipv6            use IPv6 addresses only
WARNING: failed partial clone of cluster git repo ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/: failed to sparsely clone repository ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ to directory: /tmp/jx-git-1657329244: failed to run 'git clone --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-1657329244' command in directory '/tmp', output: 'error: unknown option `filter=blob:none'
usage: git clone [<options>] [--] <repo> [<dir>]

    -v, --verbose         be more verbose
[...]
    -6, --ipv6            use IPv6 addresses only'
WARNING: falling back to default clone, without checkout patterns
about to run: git clone ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-2330179924 in dir /tmp
Cloning into '/tmp/jx-git-2330179924'...
Repository cloned to directory: /tmp/jx-git-2330179924
```
This falls back twice, finishing with a full clone.

I have also tested scenarios where the remote repository is older versions of git but this appears dependant on the version used by `jx-gitops` in its own pipeline.

As such, I am fairly confident this will work under different conditions.

2024-10-22 16:12 UTC, msvticket commented
> 
> I have also tested scenarios where the remote repository is older versions of git but this appears dependant on the version used by `jx-gitops` in its own pipeline.

There are certainly git servers that don't support `--filter blob:none`. That is the main case I'm worried about. It might be that `--filter` is just ignored in that case, but I'd like to have that verified.

What version of git on a remote repository did you try with?

If you are testing against an in house git server you should be able to disable support for filter, even though it would be support: https://git-scm.com/docs/git-config#Documentation/git-config.txt-uploadpackallowFilter

2024-10-30 16:53 UTC, GavinPJK commented
Thanks for the config tips, @msvticket. I've made more progress.

> If you are testing against an in house git server you should be able to disable support for filter, even though it would be support: https://git-scm.com/docs/git-config#Documentation/git-config.txt-uploadpackallowFilter

Based on your suggestions, I've run some more tests using a modified version of a dockerised git server running the latest version of git (https://github.com/rockstorm101/git-server-docker), where sparse checkout and filters can be set with different flags, namely https://git-scm.com/docs/git-config#Documentation/git-config.txt-coresparseCheckout and https://git-scm.com/docs/git-config#Documentation/git-config.txt-uploadpackallowFilter

Here are two cases:

1. Remote server doesn't support filters but supports `sparse-checkout`

```
$ docker run --rm --network host -v ~/.ssh:/root/.ssh -v $(pwd):/workspace -it -u root clone-test-latest
about to run: git clone --no-checkout --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-3230993895 in dir /tmp
The authenticity of host '[0.0.0.0]:2222 ([0.0.0.0]:2222)' can't be established.
ED25519 key fingerprint is SHA256:NIaCjgtyQqUQZz4L7uxlsfJY0Kx9pjnNOAVkaMbabXQ.
This key is not known by any other names.
Are you sure you want to continue connecting (yes/no/[fingerprint])? yes
Cloning into '/tmp/jx-git-3230993895'...
Warning: Permanently added '[0.0.0.0]:2222' (ED25519) to the list of known hosts.
warning: filtering not recognized by server, ignoring
warning: filtering not recognized by server, ignoring
about to run: git sparse-checkout set --no-cone .jx/gitops/source-config.yaml in dir /tmp/jx-git-3230993895
about to run: git checkout in dir /tmp/jx-git-3230993895
Your branch is up to date with 'origin/gitops-upgrade-20241014'.
Repository cloned to directory: /tmp/jx-git-3230993895
```
In this case, the "local" git ignores `--filter` and proceeds with the sparse checkout. I couldn't find a simple way of restricting or throwing an error when the `--no-checkout` command is run, so I suspect this would fall back to a full clone if this is not supported.

2. Remote server supports filters but not `sparse-checkout`:

```
about to run: git clone --no-checkout --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-1637680242 in dir m/tmp
Cloning into '/tmp/jx-git-1637680242'...
about to run: git sparse-checkout set --no-cone .jx/gitops/source-config.yaml in dir m/tmp/jx-git-1637680242
about to run: git checkout in dir m/tmp/jx-git-1637680242
fatal: could not fetch a356889c497ebee75628c864755436e2f81c9c42 from promisor remote
WARNING: failed sparse clone of cluster git repo ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/: failed to checkout sparsly: failed to run 'git checkout' command in directory '/tmp/jx-git-1637680242', output: 'fatal: could not fetch a356889c497ebee75628c864755436e2f81c9c42 from promisor remote'
WARNING: falling back to partial clone without checkout patterns
about to run: git clone --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-381148673 in dir m/tmp
Cloning into '/tmp/jx-git-381148673'...
error: Server does not allow request for unadvertised object 0017eef82965dfa5ded1a7613ab9e33065523131
[...]
fatal: could not fetch f480af2ff30238cc6c3aa8645aec4f960928caa7 from promisor remote
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/'
WARNING: failed partial clone of cluster git repo ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/: failed to sparsely clone repository ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ to directory: /tmp/jx-git-381148673: failed to run 'git clone --filter=blob:none --depth=1 ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-381148673' command in directory '/tmp', output: 'Cloning into '/tmp/jx-git-381148673'...
error: Server does not allow request for unadvertised object 0017eef82965dfa5ded1a7613ab9e33065523131
[...]
fatal: could not fetch f480af2ff30238cc6c3aa8645aec4f960928caa7 from promisor remote
warning: Clone succeeded, but checkout failed.
You can inspect what was checked out with 'git status'
and retry with 'git restore --source=HEAD :/''
WARNING: falling back to default clone, without checkout patterns
about to run: git clone ssh://git@0.0.0.0:2222/git-server/repos/JX3_Cluster_test/ /tmp/jx-git-3359681789 in dir m/tmp
Cloning into '/tmp/jx-git-3359681789'...
Repository cloned to directory: /tmp/jx-git-3359681789
```
In this case, the partial clone fails too, which I did not expect, although the full clone completes eventually. I suspect the failure of the initial checkout has something to do with the subsequent partial checkout failure but the fact the full-clone fallback works is good.

The key takeaway is that the later versions of git continue with a `warning: filtering not recognized by server, ignoring` message if certain filters are unsupported, dropping them while retrying.

2024-10-31 14:21 UTC, GavinPJK commented
@msvticket 

A few things that @Skisocks and I have discussed and seek your opinion on here:

- It looks as though if _both_ `--filter` and `git sparse-checkout set` are switched off by the remote server, that is just skipped with no checkout, i.e.: `git clone --no-checkout --depth=1 ...`. The client-side `git sparse-checkout set` then runs successfully. I suspect it's an issue with the setup using new versions of git, versus old versions where this fails hard
- The `git clone` step always successfully falls back in our testing of various configurations, which should be good enough as the previous default behaviour is supported
- Alternatively, we could include some logic to deal with cases where `warning: filtering not recognized by server, ignoring` is returned, as opposed to an error. This seems like a brittle approach to me

Any thoughts would be much appreciated!

2024-10-31 14:36 UTC, msvticket commented
I'd say that as long as the functionality doesn't break 
 
> It looks as though if _both_ `--filter` and `git sparse-checkout set` are switched off by the remote server, that is just skipped with no checkout, i.e.: `git clone --no-checkout --depth=1 ...`. The client-side `git sparse-checkout set` then runs successfully. I suspect it's an issue with the setup using new versions of git, versus old versions where this fails hard

So what is the result of `git checkout` in this case?

2024-11-01 12:52 UTC, GavinPJK commented
> > It looks as though if _both_ `--filter` and `git sparse-checkout set` are switched off by the remote server, that is just skipped with no checkout, i.e.: `git clone --no-checkout --depth=1 ...`. The client-side `git sparse-checkout set` then runs successfully. I suspect it's an issue with the setup using new versions of git, versus old versions where this fails hard
> 
> So what is the result of `git checkout` in this case?

`git sparse-checkout set --no-cone .jx/gitops/source-config.yaml` is run successfully, after running `git clone --no-checkout --depth=1 

```
$ ls -la
total 12
drwxr-xr-x    3 root     root          4096 Nov  1 12:17 .
drwx------    4 root     root          4096 Nov  1 12:17 ..
drwxr-xr-x    2 root     root          4096 Nov  1 12:17 gitops

$ tree -a ./.jx
./.jx
└── gitops
    └── source-config.yaml
```

2024-11-04 08:52 UTC, msvticket commented
> > > It looks as though if _both_ `--filter` and `git sparse-checkout set` are switched off by the remote server, that is just skipped with no checkout, i.e.: `git clone --no-checkout --depth=1 ...`. The client-side `git sparse-checkout set` then runs successfully. I suspect it's an issue with the setup using new versions of git, versus old versions where this fails hard
> > 
> > 
> > So what is the result of `git checkout` in this case?
> 
> `git sparse-checkout set --no-cone .jx/gitops/source-config.yaml` is run successfully, after ignoring the `--filter` flag, running `git clone --no-checkout --depth=1 ...`
> 
> ```
> $ ls -la
> total 12
> drwxr-xr-x    3 root     root          4096 Nov  1 12:17 .
> drwx------    4 root     root          4096 Nov  1 12:17 ..
> drwxr-xr-x    2 root     root          4096 Nov  1 12:17 gitops
> 
> $ tree -a ./.jx
> ./.jx
> └── gitops
>     └── source-config.yaml
> ```

`git sparse-checkout` doesn't check out anything. But since you above show that there are checked out files we can deduce that `git checkout` worked fine.

2024-11-04 08:55 UTC, msvticket approved these changes
I think this is tested as well as it could. It seems to me that an open question is whether
the `dir, err = gitclient.PartialCloneToDir`case in `PartialCloneClusterRepo` is actually needed.

2024-11-04 09:37 UTC, msvticket commented
/retest

2024-11-04 11:04 UTC, merged